-- AGREGAR COLUMNA
ALTER TABLE Clientes
ADD FechaCreacion TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- ELIMINAR COLUMNA
ALTER TABLE Clientes
DROP FechaCreacion;

-- MODIFICAR TIPO DE DATO COLUMNA
ALTER TABLE Clientes
MODIFY TipoDocumento VARCHAR(3) NOT NULL DEFAULT 'DNI'