# INSTRUCCION USAR BASE DE DATOS
USE CURSO45901;

-- INSTRUCCION PARA CREAR TABLA
CREATE TABLE IF NOT EXISTS Clientes 
(
	-- NOMBRE COLUMNA | TIPO DE DATO | OBLIGATORIEDAD
	TipoDocumento CHAR(3) NOT NULL, -- DNI - PAS -CI 'D  '
    Documento VARCHAR(50) NOT NULL,-- 'D'
    Telefono VARCHAR(10) NULL,
    Direccion TEXT NULL,
    Edad TINYINT NOT NULL,
    FechaNacimiento TIMESTAMP NOT NULL,
    Activo BOOL NOT NULL DEFAULT 1,
    PRIMARY KEY (TipoDocumento,Documento) -- CLAVE PRIMARIA 
);

CREATE TABLE IF NOT EXISTS Productos
(
	Id INT NOT NULL AUTO_INCREMENT,
    Descripcion VARCHAR (50),
    PRIMARY KEY (Id)
)


